project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
pull_request_title: "🌐 New Crowdin updates"
files:
  - source: /apps/web/public/locales/en/*.json
    translation: /apps/web/public/locales/%two_letters_code%/%original_file_name%
  - source: /apps/landing/public/locales/en/*.json
    translation: /apps/landing/public/locales/%two_letters_code%/%original_file_name%
  - source: /packages/emails/locales/en/*.json
    translation: /packages/emails/locales/%two_letters_code%/%original_file_name%
