project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
pull_request_title: "🌐 Update translations"
commit_message: "🌐 Update {languageName} translations ({fileName})"
files:
  [
    {
      source: "/apps/web/public/locales/en/*.json",
      translation: "/apps/web/public/locales/%two_letters_code%/%original_file_name%",
    },
  ]
