pull_request_title: "🌐 Update translations",
commit_message: "🌐 Update {languageName} translations ({fileName})"
files:
  - source: apps/app/public/locales/en/*.json
    translation: apps/app/public/locales/%two_letters_code%/%original_file_name%
