services:
  rallly_db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rallly:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    depends_on:
      rallly_db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db
      - NODE_ENV=test
      - SECRET_PASSWORD=abcdefghijklmnopqrstuvwxyz1234567890
