// This file is auto-generated by scripts/generate-timezone-data.mjs
// Do not edit manually. Run: pnpm tz:generate

export interface TimezoneEntry {
  id: string;
  city: string;
  keywords: string;
}

export const curatedTimezoneEntries: TimezoneEntry[] = [
  {
    id: "Africa/Abidjan",
    city: "Abidjan",
    keywords: "abidjan africa/abidjan gmt greenwich mean standard time",
  },
  {
    id: "Africa/Accra",
    city: "Accra",
    keywords: "accra africa/accra gmt greenwich mean standard time",
  },
  {
    id: "Africa/Addis_Ababa",
    city: "Addis Ababa",
    keywords: "addis ababa africa/addis_ababa eat east africa standard time",
  },
  {
    id: "Australia/Adelaide",
    city: "Adelaide",
    keywords:
      "adelaide australia/adelaide acst acdt central australia standard time",
  },
  {
    id: "Africa/Algiers",
    city: "Algiers",
    keywords: "algiers africa/algiers cet central european standard time",
  },
  {
    id: "Asia/Almaty",
    city: "Almaty",
    keywords: "almaty asia/almaty almt east kazakhstan standard time",
  },
  {
    id: "Europe/Amsterdam",
    city: "Amsterdam",
    keywords:
      "amsterdam europe/amsterdam cet cest central european standard time",
  },
  {
    id: "America/Anchorage",
    city: "Anchorage",
    keywords: "anchorage america/anchorage akst akdt alaska standard time",
  },
  {
    id: "Pacific/Apia",
    city: "Apia",
    keywords: "apia pacific/apia wst west samoa standard time",
  },
  {
    id: "America/Asuncion",
    city: "Asuncion",
    keywords: "asuncion america/asuncion pyt pyst paraguay standard time",
  },
  {
    id: "Europe/Athens",
    city: "Athens",
    keywords: "athens europe/athens eet eest eastern european standard time",
  },
  {
    id: "Pacific/Auckland",
    city: "Auckland",
    keywords: "auckland pacific/auckland nzst nzdt new zealand standard time",
  },
  {
    id: "Atlantic/Azores",
    city: "Azores",
    keywords: "azores atlantic/azores azot azost azores standard time",
  },
  {
    id: "Asia/Baghdad",
    city: "Baghdad",
    keywords: "baghdad asia/baghdad ast arabian standard time",
  },
  {
    id: "Asia/Baku",
    city: "Baku",
    keywords: "baku asia/baku azt azerbaijan standard time",
  },
  {
    id: "Asia/Bangkok",
    city: "Bangkok",
    keywords: "bangkok asia/bangkok ict indochina standard time",
  },
  {
    id: "America/Barbados",
    city: "Barbados",
    keywords: "barbados america/barbados ast atlantic standard time",
  },
  {
    id: "Asia/Beirut",
    city: "Beirut",
    keywords: "beirut asia/beirut eet eest eastern european standard time",
  },
  {
    id: "Europe/Belgrade",
    city: "Belgrade",
    keywords:
      "belgrade europe/belgrade cet cest central european standard time",
  },
  {
    id: "Europe/Berlin",
    city: "Berlin",
    keywords: "berlin europe/berlin cet cest central european standard time",
  },
  {
    id: "America/Bogota",
    city: "Bogota",
    keywords: "bogota america/bogota cot colombia standard time",
  },
  {
    id: "Australia/Brisbane",
    city: "Brisbane",
    keywords: "brisbane australia/brisbane aest brisbane standard time",
  },
  {
    id: "Europe/Brussels",
    city: "Brussels",
    keywords:
      "brussels europe/brussels cet cest central european standard time",
  },
  {
    id: "Europe/Bucharest",
    city: "Bucharest",
    keywords:
      "bucharest europe/bucharest eet eest eastern european standard time",
  },
  {
    id: "Europe/Budapest",
    city: "Budapest",
    keywords:
      "budapest europe/budapest cet cest central european standard time",
  },
  {
    id: "Africa/Cairo",
    city: "Cairo",
    keywords: "cairo africa/cairo eet eastern european standard time",
  },
  {
    id: "America/Cancun",
    city: "Cancun",
    keywords: "cancun america/cancun est eastern standard time",
  },
  {
    id: "Atlantic/Cape_Verde",
    city: "Cape Verde",
    keywords: "cape verde atlantic/cape_verde cvt cape verde standard time",
  },
  {
    id: "America/Caracas",
    city: "Caracas",
    keywords: "caracas america/caracas vet venezuela standard time",
  },
  {
    id: "Africa/Casablanca",
    city: "Casablanca",
    keywords:
      "casablanca africa/casablanca wet west morocco standard standard time",
  },
  {
    id: "America/Chicago",
    city: "Chicago",
    keywords: "chicago america/chicago cst cdt central standard time",
  },
  {
    id: "Asia/Colombo",
    city: "Colombo",
    keywords: "colombo asia/colombo ist india standard time",
  },
  {
    id: "Europe/Copenhagen",
    city: "Copenhagen",
    keywords:
      "copenhagen europe/copenhagen cet cest central european standard time",
  },
  {
    id: "Australia/Darwin",
    city: "Darwin",
    keywords: "darwin australia/darwin acst australian central standard time",
  },
  {
    id: "America/Denver",
    city: "Denver",
    keywords: "denver america/denver mst mdt mountain standard time",
  },
  {
    id: "Asia/Dhaka",
    city: "Dhaka",
    keywords: "dhaka asia/dhaka bst bangladesh standard time",
  },
  {
    id: "Asia/Dubai",
    city: "Dubai",
    keywords: "dubai asia/dubai gst gulf standard time",
  },
  {
    id: "Europe/Dublin",
    city: "Dublin",
    keywords: "dublin europe/dublin gmt ist irish standard time",
  },
  {
    id: "America/Edmonton",
    city: "Edmonton",
    keywords: "edmonton america/edmonton mst mdt mountain standard time",
  },
  {
    id: "Pacific/Fiji",
    city: "Fiji",
    keywords: "fiji pacific/fiji fjt fjt fiji standard time",
  },
  {
    id: "Pacific/Guadalcanal",
    city: "Guadalcanal",
    keywords:
      "guadalcanal pacific/guadalcanal sbt solomon islands standard time",
  },
  {
    id: "Pacific/Guam",
    city: "Guam",
    keywords: "guam pacific/guam chst chamorro standard time",
  },
  {
    id: "America/Guatemala",
    city: "Guatemala",
    keywords: "guatemala america/guatemala cst central standard time",
  },
  {
    id: "America/Halifax",
    city: "Halifax",
    keywords: "halifax america/halifax ast adt atlantic standard time",
  },
  {
    id: "America/Havana",
    city: "Havana",
    keywords: "havana america/havana hncu hecu cuba standard time",
  },
  {
    id: "Europe/Helsinki",
    city: "Helsinki",
    keywords:
      "helsinki europe/helsinki eet eest eastern european standard time",
  },
  {
    id: "Asia/Hong_Kong",
    city: "Hong Kong",
    keywords: "hong kong asia/hong_kong hkt hong kong standard time",
  },
  {
    id: "Pacific/Honolulu",
    city: "Honolulu",
    keywords: "honolulu pacific/honolulu hast hawaii-aleutian standard time",
  },
  {
    id: "America/Indianapolis",
    city: "Indianapolis",
    keywords: "indianapolis america/indianapolis est edt eastern standard time",
  },
  {
    id: "Europe/Istanbul",
    city: "Istanbul",
    keywords: "istanbul europe/istanbul trt turkey standard time",
  },
  {
    id: "Asia/Jakarta",
    city: "Jakarta",
    keywords: "jakarta asia/jakarta wib western indonesia standard time",
  },
  {
    id: "America/Jamaica",
    city: "Jamaica",
    keywords: "jamaica america/jamaica est eastern standard time",
  },
  {
    id: "Asia/Jerusalem",
    city: "Jerusalem",
    keywords: "jerusalem asia/jerusalem ist idt israel standard time",
  },
  {
    id: "Africa/Johannesburg",
    city: "Johannesburg",
    keywords:
      "johannesburg africa/johannesburg sast south africa standard time",
  },
  {
    id: "Asia/Kabul",
    city: "Kabul",
    keywords: "kabul asia/kabul aft afghanistan standard time",
  },
  {
    id: "Asia/Kamchatka",
    city: "Kamchatka",
    keywords:
      "kamchatka asia/kamchatka pett petropavlovsk-kamchatski standard time",
  },
  {
    id: "Asia/Karachi",
    city: "Karachi",
    keywords: "karachi asia/karachi pkt pakistan standard time",
  },
  {
    id: "Asia/Krasnoyarsk",
    city: "Krasnoyarsk",
    keywords: "krasnoyarsk asia/krasnoyarsk krat krasnoyarsk standard time",
  },
  {
    id: "Asia/Kuala_Lumpur",
    city: "Kuala Lumpur",
    keywords: "kuala lumpur asia/kuala_lumpur myt malaysia standard time",
  },
  {
    id: "Asia/Kuwait",
    city: "Kuwait",
    keywords: "kuwait asia/kuwait ast arabian standard time",
  },
  {
    id: "America/La_Paz",
    city: "La Paz",
    keywords: "la paz america/la_paz bot bolivia standard time",
  },
  {
    id: "Africa/Lagos",
    city: "Lagos",
    keywords: "lagos africa/lagos wat west africa standard time",
  },
  {
    id: "America/Lima",
    city: "Lima",
    keywords: "lima america/lima pet peru standard time",
  },
  {
    id: "Europe/Lisbon",
    city: "Lisbon",
    keywords: "lisbon europe/lisbon wet west western european standard time",
  },
  {
    id: "Europe/London",
    city: "London",
    keywords: "london europe/london gmt bst british standard time",
  },
  {
    id: "America/Los_Angeles",
    city: "Los Angeles",
    keywords: "los angeles america/los_angeles pst pdt pacific standard time",
  },
  {
    id: "Asia/Macau",
    city: "Macau",
    keywords: "macau asia/macau cst china standard time",
  },
  {
    id: "Europe/Madrid",
    city: "Madrid",
    keywords: "madrid europe/madrid cet cest central european standard time",
  },
  {
    id: "Asia/Magadan",
    city: "Magadan",
    keywords: "magadan asia/magadan magt magadan standard time",
  },
  {
    id: "Asia/Manila",
    city: "Manila",
    keywords: "manila asia/manila phst philippine standard time",
  },
  {
    id: "Indian/Mauritius",
    city: "Mauritius",
    keywords: "mauritius indian/mauritius mut mauritius standard time",
  },
  {
    id: "Australia/Melbourne",
    city: "Melbourne",
    keywords:
      "melbourne australia/melbourne aest aedt eastern australia standard time",
  },
  {
    id: "America/Mexico_City",
    city: "Mexico City",
    keywords:
      "mexico city america/mexico_city cst cdt central mexico standard time",
  },
  {
    id: "Europe/Minsk",
    city: "Minsk",
    keywords: "minsk europe/minsk msk moscow standard time",
  },
  {
    id: "Africa/Monrovia",
    city: "Monrovia",
    keywords: "monrovia africa/monrovia gmt greenwich mean standard time",
  },
  {
    id: "America/Montevideo",
    city: "Montevideo",
    keywords: "montevideo america/montevideo uyt uruguay standard time",
  },
  {
    id: "Europe/Moscow",
    city: "Moscow",
    keywords: "moscow europe/moscow msk moscow standard time",
  },
  {
    id: "Africa/Nairobi",
    city: "Nairobi",
    keywords: "nairobi africa/nairobi eat east africa standard time",
  },
  {
    id: "America/New_York",
    city: "New York",
    keywords: "new york america/new_york est edt eastern standard time",
  },
  {
    id: "America/Noronha",
    city: "Noronha",
    keywords: "noronha america/noronha fnt fernando de noronha standard time",
  },
  {
    id: "Pacific/Noumea",
    city: "Noumea",
    keywords: "noumea pacific/noumea nct new caledonia standard time",
  },
  {
    id: "Asia/Omsk",
    city: "Omsk",
    keywords: "omsk asia/omsk omst omsk standard time",
  },
  {
    id: "Europe/Oslo",
    city: "Oslo",
    keywords: "oslo europe/oslo cet cest central european standard time",
  },
  {
    id: "Pacific/Pago_Pago",
    city: "Pago Pago",
    keywords: "pago pago pacific/pago_pago sst samoa standard time",
  },
  {
    id: "America/Panama",
    city: "Panama",
    keywords: "panama america/panama est eastern standard time",
  },
  {
    id: "Europe/Paris",
    city: "Paris",
    keywords: "paris europe/paris cet cest central european standard time",
  },
  {
    id: "Australia/Perth",
    city: "Perth",
    keywords: "perth australia/perth awst western australia standard time",
  },
  {
    id: "America/Phoenix",
    city: "Phoenix",
    keywords: "phoenix america/phoenix mst mountain standard time",
  },
  {
    id: "Pacific/Port_Moresby",
    city: "Port Moresby",
    keywords:
      "port moresby pacific/port_moresby pgt papua new guinea standard time",
  },
  {
    id: "Europe/Prague",
    city: "Prague",
    keywords: "prague europe/prague cet cest central european standard time",
  },
  {
    id: "America/Puerto_Rico",
    city: "Puerto Rico",
    keywords: "puerto rico america/puerto_rico ast atlantic standard time",
  },
  {
    id: "Asia/Qatar",
    city: "Qatar",
    keywords: "qatar asia/qatar ast arabian standard time",
  },
  {
    id: "Atlantic/Reykjavik",
    city: "Reykjavik",
    keywords: "reykjavik atlantic/reykjavik gmt greenwich mean standard time",
  },
  {
    id: "Europe/Riga",
    city: "Riga",
    keywords: "riga europe/riga eet eest eastern european standard time",
  },
  {
    id: "Asia/Riyadh",
    city: "Riyadh",
    keywords: "riyadh asia/riyadh ast arabian standard time",
  },
  {
    id: "Europe/Rome",
    city: "Rome",
    keywords: "rome europe/rome cet cest central european standard time",
  },
  {
    id: "America/Santiago",
    city: "Santiago",
    keywords: "santiago america/santiago clt clst chile standard time",
  },
  {
    id: "America/Santo_Domingo",
    city: "Santo Domingo",
    keywords: "santo domingo america/santo_domingo ast atlantic standard time",
  },
  {
    id: "America/Sao_Paulo",
    city: "Sao Paulo",
    keywords: "sao paulo america/sao_paulo brt brasilia standard time",
  },
  {
    id: "Asia/Seoul",
    city: "Seoul",
    keywords: "seoul asia/seoul kst korean standard time",
  },
  {
    id: "Asia/Shanghai",
    city: "Shanghai",
    keywords: "shanghai asia/shanghai cst china standard time",
  },
  {
    id: "Asia/Singapore",
    city: "Singapore",
    keywords: "singapore asia/singapore sgt singapore standard time",
  },
  {
    id: "Europe/Sofia",
    city: "Sofia",
    keywords: "sofia europe/sofia eet eest eastern european standard time",
  },
  {
    id: "Atlantic/South_Georgia",
    city: "South Georgia",
    keywords:
      "south georgia atlantic/south_georgia gst south georgia standard time",
  },
  {
    id: "America/St_Johns",
    city: "St Johns",
    keywords: "st johns america/st_johns hntn hetn newfoundland standard time",
  },
  {
    id: "Europe/Stockholm",
    city: "Stockholm",
    keywords:
      "stockholm europe/stockholm cet cest central european standard time",
  },
  {
    id: "Australia/Sydney",
    city: "Sydney",
    keywords:
      "sydney australia/sydney aest aedt eastern australia standard time",
  },
  {
    id: "Asia/Taipei",
    city: "Taipei",
    keywords: "taipei asia/taipei cst taipei standard time",
  },
  {
    id: "Europe/Tallinn",
    city: "Tallinn",
    keywords: "tallinn europe/tallinn eet eest eastern european standard time",
  },
  {
    id: "Asia/Tashkent",
    city: "Tashkent",
    keywords: "tashkent asia/tashkent uzt uzbekistan standard time",
  },
  {
    id: "Asia/Tbilisi",
    city: "Tbilisi",
    keywords: "tbilisi asia/tbilisi get georgia standard time",
  },
  {
    id: "Asia/Tehran",
    city: "Tehran",
    keywords: "tehran asia/tehran irst iran standard time",
  },
  {
    id: "America/Tijuana",
    city: "Tijuana",
    keywords: "tijuana america/tijuana pst pdt pacific standard time",
  },
  {
    id: "Asia/Tokyo",
    city: "Tokyo",
    keywords: "tokyo asia/tokyo jst japan standard time",
  },
  {
    id: "Pacific/Tongatapu",
    city: "Tongatapu",
    keywords: "tongatapu pacific/tongatapu tot tonga standard time",
  },
  {
    id: "America/Toronto",
    city: "Toronto",
    keywords: "toronto america/toronto est edt eastern standard time",
  },
  {
    id: "Africa/Tunis",
    city: "Tunis",
    keywords: "tunis africa/tunis cet central european standard time",
  },
  {
    id: "America/Vancouver",
    city: "Vancouver",
    keywords: "vancouver america/vancouver pst pdt pacific standard time",
  },
  {
    id: "Europe/Vienna",
    city: "Vienna",
    keywords: "vienna europe/vienna cet cest central european standard time",
  },
  {
    id: "Europe/Vilnius",
    city: "Vilnius",
    keywords: "vilnius europe/vilnius eet eest eastern european standard time",
  },
  {
    id: "Europe/Warsaw",
    city: "Warsaw",
    keywords: "warsaw europe/warsaw cet cest central european standard time",
  },
  {
    id: "America/Winnipeg",
    city: "Winnipeg",
    keywords: "winnipeg america/winnipeg cst cdt central standard time",
  },
  {
    id: "Asia/Yakutsk",
    city: "Yakutsk",
    keywords: "yakutsk asia/yakutsk yakt yakutsk standard time",
  },
  {
    id: "Asia/Yekaterinburg",
    city: "Yekaterinburg",
    keywords:
      "yekaterinburg asia/yekaterinburg yekt yekaterinburg standard time",
  },
  {
    id: "Asia/Yerevan",
    city: "Yerevan",
    keywords: "yerevan asia/yerevan amt armenia standard time",
  },
  {
    id: "Europe/Zurich",
    city: "Zurich",
    keywords: "zurich europe/zurich cet cest central european standard time",
  },
];

export const otherTimezoneEntries: TimezoneEntry[] = [
  {
    id: "America/Adak",
    city: "Adak",
    keywords: "adak america/adak hst hdt aleutian standard standard time",
  },
  {
    id: "Asia/Aden",
    city: "Aden",
    keywords: "aden asia/aden ast arabian standard time",
  },
  {
    id: "Asia/Amman",
    city: "Amman",
    keywords: "amman asia/amman eet eest eastern european standard time",
  },
  {
    id: "Asia/Anadyr",
    city: "Anadyr",
    keywords: "anadyr asia/anadyr anat anadyr standard time",
  },
  {
    id: "Europe/Andorra",
    city: "Andorra",
    keywords: "andorra europe/andorra cet cest central european standard time",
  },
  {
    id: "America/Anguilla",
    city: "Anguilla",
    keywords: "anguilla america/anguilla ast atlantic standard time",
  },
  {
    id: "Indian/Antananarivo",
    city: "Antananarivo",
    keywords: "antananarivo indian/antananarivo eat east africa standard time",
  },
  {
    id: "America/Antigua",
    city: "Antigua",
    keywords: "antigua america/antigua ast atlantic standard time",
  },
  {
    id: "Asia/Aqtau",
    city: "Aqtau",
    keywords: "aqtau asia/aqtau almt west kazakhstan standard time",
  },
  {
    id: "Asia/Aqtobe",
    city: "Aqtobe",
    keywords: "aqtobe asia/aqtobe almt west kazakhstan standard time",
  },
  {
    id: "America/Araguaina",
    city: "Araguaina",
    keywords: "araguaina america/araguaina brt brasilia standard time",
  },
  {
    id: "America/Aruba",
    city: "Aruba",
    keywords: "aruba america/aruba ast atlantic standard time",
  },
  {
    id: "Asia/Ashgabat",
    city: "Ashgabat",
    keywords: "ashgabat asia/ashgabat tmt turkmenistan standard time",
  },
  {
    id: "Africa/Asmera",
    city: "Asmera",
    keywords: "asmera africa/asmera eat east africa standard time",
  },
  {
    id: "Europe/Astrakhan",
    city: "Astrakhan",
    keywords: "astrakhan europe/astrakhan msk moscow standard time",
  },
  {
    id: "Asia/Atyrau",
    city: "Atyrau",
    keywords: "atyrau asia/atyrau almt west kazakhstan standard time",
  },
  {
    id: "America/Bahia",
    city: "Bahia",
    keywords: "bahia america/bahia brt brasilia standard time",
  },
  {
    id: "America/Bahia_Banderas",
    city: "Bahia Banderas",
    keywords:
      "bahia banderas america/bahia_banderas cst cdt central mexico standard time",
  },
  {
    id: "Asia/Bahrain",
    city: "Bahrain",
    keywords: "bahrain asia/bahrain ast arabian standard time",
  },
  {
    id: "Africa/Bamako",
    city: "Bamako",
    keywords: "bamako africa/bamako gmt greenwich mean standard time",
  },
  {
    id: "Africa/Bangui",
    city: "Bangui",
    keywords: "bangui africa/bangui wat west africa standard time",
  },
  {
    id: "Africa/Banjul",
    city: "Banjul",
    keywords: "banjul africa/banjul gmt greenwich mean standard time",
  },
  {
    id: "Asia/Barnaul",
    city: "Barnaul",
    keywords: "barnaul asia/barnaul krat krasnoyarsk standard time",
  },
  {
    id: "America/Belem",
    city: "Belem",
    keywords: "belem america/belem brt brasilia standard time",
  },
  {
    id: "America/Belize",
    city: "Belize",
    keywords: "belize america/belize cst central standard time",
  },
  {
    id: "Atlantic/Bermuda",
    city: "Bermuda",
    keywords: "bermuda atlantic/bermuda ast adt atlantic standard time",
  },
  {
    id: "America/North_Dakota/Beulah",
    city: "Beulah",
    keywords:
      "beulah america/north_dakota/beulah cst cdt central standard time",
  },
  {
    id: "Asia/Bishkek",
    city: "Bishkek",
    keywords: "bishkek asia/bishkek kgt kyrgyzstan standard time",
  },
  {
    id: "Africa/Bissau",
    city: "Bissau",
    keywords: "bissau africa/bissau gmt greenwich mean standard time",
  },
  {
    id: "America/Blanc-Sablon",
    city: "Blanc-Sablon",
    keywords: "blanc-sablon america/blanc-sablon ast atlantic standard time",
  },
  {
    id: "Africa/Blantyre",
    city: "Blantyre",
    keywords: "blantyre africa/blantyre cat central africa standard time",
  },
  {
    id: "America/Boa_Vista",
    city: "Boa Vista",
    keywords: "boa vista america/boa_vista amt amazon standard time",
  },
  {
    id: "America/Boise",
    city: "Boise",
    keywords: "boise america/boise mst mdt mountain standard time",
  },
  {
    id: "Pacific/Bougainville",
    city: "Bougainville",
    keywords:
      "bougainville pacific/bougainville pgt papua new guinea standard time",
  },
  {
    id: "Europe/Bratislava",
    city: "Bratislava",
    keywords:
      "bratislava europe/bratislava cet cest central european standard time",
  },
  {
    id: "Africa/Brazzaville",
    city: "Brazzaville",
    keywords: "brazzaville africa/brazzaville wat west africa standard time",
  },
  {
    id: "Australia/Broken_Hill",
    city: "Broken Hill",
    keywords:
      "broken hill australia/broken_hill acst acdt central australia standard time",
  },
  {
    id: "Asia/Brunei",
    city: "Brunei",
    keywords: "brunei asia/brunei bnt brunei darussalam standard time",
  },
  {
    id: "America/Buenos_Aires",
    city: "Buenos Aires",
    keywords: "buenos aires america/buenos_aires art argentina standard time",
  },
  {
    id: "Africa/Bujumbura",
    city: "Bujumbura",
    keywords: "bujumbura africa/bujumbura cat central africa standard time",
  },
  {
    id: "Europe/Busingen",
    city: "Busingen",
    keywords:
      "busingen europe/busingen cet cest central european standard time",
  },
  {
    id: "Asia/Calcutta",
    city: "Calcutta",
    keywords: "calcutta asia/calcutta ist india standard time",
  },
  {
    id: "America/Cambridge_Bay",
    city: "Cambridge Bay",
    keywords:
      "cambridge bay america/cambridge_bay mst mdt mountain standard time",
  },
  {
    id: "America/Campo_Grande",
    city: "Campo Grande",
    keywords: "campo grande america/campo_grande amt amazon standard time",
  },
  {
    id: "Atlantic/Canary",
    city: "Canary",
    keywords: "canary atlantic/canary wet west western european standard time",
  },
  {
    id: "Antarctica/Casey",
    city: "Casey",
    keywords: "casey antarctica/casey cast cast casey standard time",
  },
  {
    id: "America/Catamarca",
    city: "Catamarca",
    keywords: "catamarca america/catamarca art argentina standard time",
  },
  {
    id: "America/Cayenne",
    city: "Cayenne",
    keywords: "cayenne america/cayenne gft french guiana standard time",
  },
  {
    id: "America/Cayman",
    city: "Cayman",
    keywords: "cayman america/cayman est eastern standard time",
  },
  {
    id: "America/North_Dakota/Center",
    city: "Center",
    keywords:
      "center america/north_dakota/center cst cdt central standard time",
  },
  {
    id: "Africa/Ceuta",
    city: "Ceuta",
    keywords: "ceuta africa/ceuta cet cest central european standard time",
  },
  {
    id: "Indian/Chagos",
    city: "Chagos",
    keywords: "chagos indian/chagos iot indian ocean standard time",
  },
  {
    id: "Pacific/Chatham",
    city: "Chatham",
    keywords: "chatham pacific/chatham chast chadt chatham standard time",
  },
  {
    id: "America/Chihuahua",
    city: "Chihuahua",
    keywords:
      "chihuahua america/chihuahua hnpmx hepmx mexican pacific standard time",
  },
  {
    id: "Europe/Chisinau",
    city: "Chisinau",
    keywords:
      "chisinau europe/chisinau eet eest eastern european standard time",
  },
  {
    id: "Asia/Chita",
    city: "Chita",
    keywords: "chita asia/chita yakt yakutsk standard time",
  },
  {
    id: "Indian/Christmas",
    city: "Christmas",
    keywords: "christmas indian/christmas cxt christmas island standard time",
  },
  {
    id: "America/Ciudad_Juarez",
    city: "Ciudad Juarez",
    keywords: "ciudad juarez america/ciudad_juarez",
  },
  {
    id: "Indian/Cocos",
    city: "Cocos",
    keywords: "cocos indian/cocos cct cocos islands standard time",
  },
  {
    id: "Indian/Comoro",
    city: "Comoro",
    keywords: "comoro indian/comoro eat east africa standard time",
  },
  {
    id: "Africa/Conakry",
    city: "Conakry",
    keywords: "conakry africa/conakry gmt greenwich mean standard time",
  },
  {
    id: "America/Coral_Harbour",
    city: "Coral Harbour",
    keywords: "coral harbour america/coral_harbour est eastern standard time",
  },
  {
    id: "America/Cordoba",
    city: "Cordoba",
    keywords: "cordoba america/cordoba art argentina standard time",
  },
  {
    id: "America/Costa_Rica",
    city: "Costa Rica",
    keywords: "costa rica america/costa_rica cst central standard time",
  },
  {
    id: "America/Coyhaique",
    city: "Coyhaique",
    keywords: "coyhaique america/coyhaique",
  },
  {
    id: "America/Creston",
    city: "Creston",
    keywords: "creston america/creston mst mountain standard time",
  },
  {
    id: "America/Cuiaba",
    city: "Cuiaba",
    keywords: "cuiaba america/cuiaba amt amazon standard time",
  },
  {
    id: "America/Curacao",
    city: "Curacao",
    keywords: "curacao america/curacao ast atlantic standard time",
  },
  {
    id: "Africa/Dakar",
    city: "Dakar",
    keywords: "dakar africa/dakar gmt greenwich mean standard time",
  },
  {
    id: "Asia/Damascus",
    city: "Damascus",
    keywords: "damascus asia/damascus eet eest eastern european standard time",
  },
  {
    id: "America/Danmarkshavn",
    city: "Danmarkshavn",
    keywords:
      "danmarkshavn america/danmarkshavn gmt greenwich mean standard time",
  },
  {
    id: "Africa/Dar_es_Salaam",
    city: "Dar es Salaam",
    keywords:
      "dar es salaam africa/dar_es_salaam eat east africa standard time",
  },
  {
    id: "Antarctica/Davis",
    city: "Davis",
    keywords: "davis antarctica/davis davt davis standard time",
  },
  {
    id: "America/Dawson",
    city: "Dawson",
    keywords: "dawson america/dawson mst mountain standard time",
  },
  {
    id: "America/Dawson_Creek",
    city: "Dawson Creek",
    keywords: "dawson creek america/dawson_creek mst mountain standard time",
  },
  {
    id: "America/Detroit",
    city: "Detroit",
    keywords: "detroit america/detroit est edt eastern standard time",
  },
  {
    id: "Asia/Dili",
    city: "Dili",
    keywords: "dili asia/dili tlt east timor standard time",
  },
  {
    id: "Africa/Djibouti",
    city: "Djibouti",
    keywords: "djibouti africa/djibouti eat east africa standard time",
  },
  {
    id: "America/Dominica",
    city: "Dominica",
    keywords: "dominica america/dominica ast atlantic standard time",
  },
  {
    id: "Africa/Douala",
    city: "Douala",
    keywords: "douala africa/douala wat west africa standard time",
  },
  {
    id: "Antarctica/DumontDUrville",
    city: "DumontDUrville",
    keywords:
      "dumontdurville antarctica/dumontdurville pgt papua new guinea standard time",
  },
  {
    id: "Asia/Dushanbe",
    city: "Dushanbe",
    keywords: "dushanbe asia/dushanbe tjt tajikistan standard time",
  },
  {
    id: "Pacific/Easter",
    city: "Easter",
    keywords: "easter pacific/easter east easst easter island standard time",
  },
  {
    id: "Pacific/Efate",
    city: "Efate",
    keywords: "efate pacific/efate vut vanuatu standard time",
  },
  {
    id: "America/Eirunepe",
    city: "Eirunepe",
    keywords: "eirunepe america/eirunepe act acre standard time",
  },
  {
    id: "Africa/El_Aaiun",
    city: "El Aaiun",
    keywords:
      "el aaiun africa/el_aaiun wet west morocco standard standard time",
  },
  {
    id: "America/El_Salvador",
    city: "El Salvador",
    keywords: "el salvador america/el_salvador cst central standard time",
  },
  {
    id: "Pacific/Enderbury",
    city: "Enderbury",
    keywords: "enderbury pacific/enderbury phot phoenix islands standard time",
  },
  {
    id: "Australia/Eucla",
    city: "Eucla",
    keywords:
      "eucla australia/eucla acwst australian central western standard time",
  },
  {
    id: "Atlantic/Faeroe",
    city: "Faeroe",
    keywords: "faeroe atlantic/faeroe wet west western european standard time",
  },
  {
    id: "Pacific/Fakaofo",
    city: "Fakaofo",
    keywords: "fakaofo pacific/fakaofo tkt tokelau standard time",
  },
  {
    id: "Asia/Famagusta",
    city: "Famagusta",
    keywords:
      "famagusta asia/famagusta eet eest eastern european standard time",
  },
  {
    id: "America/Fort_Nelson",
    city: "Fort Nelson",
    keywords: "fort nelson america/fort_nelson mst mountain standard time",
  },
  {
    id: "America/Fortaleza",
    city: "Fortaleza",
    keywords: "fortaleza america/fortaleza brt brasilia standard time",
  },
  {
    id: "Africa/Freetown",
    city: "Freetown",
    keywords: "freetown africa/freetown gmt greenwich mean standard time",
  },
  {
    id: "Pacific/Funafuti",
    city: "Funafuti",
    keywords: "funafuti pacific/funafuti tvt tuvalu standard time",
  },
  {
    id: "Africa/Gaborone",
    city: "Gaborone",
    keywords: "gaborone africa/gaborone cat central africa standard time",
  },
  {
    id: "Pacific/Galapagos",
    city: "Galapagos",
    keywords: "galapagos pacific/galapagos cot colombia standard time",
  },
  {
    id: "Pacific/Gambier",
    city: "Gambier",
    keywords: "gambier pacific/gambier gamt gambier standard time",
  },
  {
    id: "Asia/Gaza",
    city: "Gaza",
    keywords: "gaza asia/gaza eet eest eastern european standard time",
  },
  {
    id: "Europe/Gibraltar",
    city: "Gibraltar",
    keywords:
      "gibraltar europe/gibraltar cet cest central european standard time",
  },
  {
    id: "America/Glace_Bay",
    city: "Glace Bay",
    keywords: "glace bay america/glace_bay ast adt atlantic standard time",
  },
  {
    id: "America/Godthab",
    city: "Godthab",
    keywords: "godthab america/godthab wgt wgst west greenland standard time",
  },
  {
    id: "America/Goose_Bay",
    city: "Goose Bay",
    keywords: "goose bay america/goose_bay ast adt atlantic standard time",
  },
  {
    id: "America/Grand_Turk",
    city: "Grand Turk",
    keywords: "grand turk america/grand_turk est edt eastern standard time",
  },
  {
    id: "America/Grenada",
    city: "Grenada",
    keywords: "grenada america/grenada ast atlantic standard time",
  },
  {
    id: "America/Guadeloupe",
    city: "Guadeloupe",
    keywords: "guadeloupe america/guadeloupe ast atlantic standard time",
  },
  {
    id: "America/Guayaquil",
    city: "Guayaquil",
    keywords: "guayaquil america/guayaquil ect ecuador standard time",
  },
  {
    id: "Europe/Guernsey",
    city: "Guernsey",
    keywords: "guernsey europe/guernsey gmt bst british standard time",
  },
  {
    id: "America/Guyana",
    city: "Guyana",
    keywords: "guyana america/guyana gyt guyana standard time",
  },
  {
    id: "Africa/Harare",
    city: "Harare",
    keywords: "harare africa/harare cat central africa standard time",
  },
  {
    id: "Asia/Hebron",
    city: "Hebron",
    keywords: "hebron asia/hebron eet eest eastern european standard time",
  },
  {
    id: "America/Hermosillo",
    city: "Hermosillo",
    keywords:
      "hermosillo america/hermosillo hnpmx mexican pacific standard time",
  },
  {
    id: "Australia/Hobart",
    city: "Hobart",
    keywords:
      "hobart australia/hobart aest aedt eastern australia standard time",
  },
  {
    id: "Asia/Hovd",
    city: "Hovd",
    keywords: "hovd asia/hovd hovt hovd standard time",
  },
  {
    id: "America/Indiana/Indianapolis",
    city: "Indianapolis",
    keywords:
      "indianapolis america/indiana/indianapolis est edt eastern standard time",
  },
  {
    id: "America/Inuvik",
    city: "Inuvik",
    keywords: "inuvik america/inuvik mst mdt mountain standard time",
  },
  {
    id: "America/Iqaluit",
    city: "Iqaluit",
    keywords: "iqaluit america/iqaluit est edt eastern standard time",
  },
  {
    id: "Asia/Irkutsk",
    city: "Irkutsk",
    keywords: "irkutsk asia/irkutsk irkt irkutsk standard time",
  },
  {
    id: "Europe/Isle_of_Man",
    city: "Isle of Man",
    keywords: "isle of man europe/isle_of_man gmt bst british standard time",
  },
  {
    id: "Asia/Jayapura",
    city: "Jayapura",
    keywords: "jayapura asia/jayapura wit eastern indonesia standard time",
  },
  {
    id: "Europe/Jersey",
    city: "Jersey",
    keywords: "jersey europe/jersey gmt bst british standard time",
  },
  {
    id: "Pacific/Johnston",
    city: "Johnston",
    keywords: "johnston pacific/johnston hast hawaii-aleutian standard time",
  },
  {
    id: "Africa/Juba",
    city: "Juba",
    keywords: "juba africa/juba cat central africa standard time",
  },
  {
    id: "America/Jujuy",
    city: "Jujuy",
    keywords: "jujuy america/jujuy art argentina standard time",
  },
  {
    id: "America/Juneau",
    city: "Juneau",
    keywords: "juneau america/juneau akst akdt alaska standard time",
  },
  {
    id: "Europe/Kaliningrad",
    city: "Kaliningrad",
    keywords:
      "kaliningrad europe/kaliningrad eet eastern european standard time",
  },
  {
    id: "Africa/Kampala",
    city: "Kampala",
    keywords: "kampala africa/kampala eat east africa standard time",
  },
  {
    id: "Asia/Katmandu",
    city: "Katmandu",
    keywords: "katmandu asia/katmandu npt nepal standard time",
  },
  {
    id: "Indian/Kerguelen",
    city: "Kerguelen",
    keywords:
      "kerguelen indian/kerguelen tft french southern & antarctic standard time",
  },
  {
    id: "Asia/Khandyga",
    city: "Khandyga",
    keywords: "khandyga asia/khandyga yakt yakutsk standard time",
  },
  {
    id: "Africa/Khartoum",
    city: "Khartoum",
    keywords: "khartoum africa/khartoum cat central africa standard time",
  },
  {
    id: "Europe/Kiev",
    city: "Kiev",
    keywords: "kiev europe/kiev eet eest eastern european standard time",
  },
  {
    id: "Africa/Kigali",
    city: "Kigali",
    keywords: "kigali africa/kigali cat central africa standard time",
  },
  {
    id: "Africa/Kinshasa",
    city: "Kinshasa",
    keywords: "kinshasa africa/kinshasa wat west africa standard time",
  },
  {
    id: "Pacific/Kiritimati",
    city: "Kiritimati",
    keywords: "kiritimati pacific/kiritimati lint line islands standard time",
  },
  {
    id: "Europe/Kirov",
    city: "Kirov",
    keywords: "kirov europe/kirov msk moscow standard time",
  },
  {
    id: "America/Indiana/Knox",
    city: "Knox",
    keywords: "knox america/indiana/knox cst cdt central standard time",
  },
  {
    id: "Pacific/Kosrae",
    city: "Kosrae",
    keywords: "kosrae pacific/kosrae kost kosrae standard time",
  },
  {
    id: "America/Kralendijk",
    city: "Kralendijk",
    keywords: "kralendijk america/kralendijk ast atlantic standard time",
  },
  {
    id: "Asia/Kuching",
    city: "Kuching",
    keywords: "kuching asia/kuching myt malaysia standard time",
  },
  {
    id: "Pacific/Kwajalein",
    city: "Kwajalein",
    keywords: "kwajalein pacific/kwajalein mht marshall islands standard time",
  },
  {
    id: "America/Argentina/La_Rioja",
    city: "La Rioja",
    keywords: "la rioja america/argentina/la_rioja art argentina standard time",
  },
  {
    id: "Africa/Libreville",
    city: "Libreville",
    keywords: "libreville africa/libreville wat west africa standard time",
  },
  {
    id: "Australia/Lindeman",
    city: "Lindeman",
    keywords: "lindeman australia/lindeman aest brisbane standard time",
  },
  {
    id: "Europe/Ljubljana",
    city: "Ljubljana",
    keywords:
      "ljubljana europe/ljubljana cet cest central european standard time",
  },
  {
    id: "Africa/Lome",
    city: "Lome",
    keywords: "lome africa/lome gmt greenwich mean standard time",
  },
  {
    id: "Arctic/Longyearbyen",
    city: "Longyearbyen",
    keywords:
      "longyearbyen arctic/longyearbyen cet cest central european standard time",
  },
  {
    id: "Australia/Lord_Howe",
    city: "Lord Howe",
    keywords: "lord howe australia/lord_howe lhst lhdt lord howe standard time",
  },
  {
    id: "America/Louisville",
    city: "Louisville",
    keywords: "louisville america/louisville est edt eastern standard time",
  },
  {
    id: "America/Lower_Princes",
    city: "Lower Princes",
    keywords: "lower princes america/lower_princes ast atlantic standard time",
  },
  {
    id: "Africa/Luanda",
    city: "Luanda",
    keywords: "luanda africa/luanda wat west africa standard time",
  },
  {
    id: "Africa/Lubumbashi",
    city: "Lubumbashi",
    keywords: "lubumbashi africa/lubumbashi cat central africa standard time",
  },
  {
    id: "Africa/Lusaka",
    city: "Lusaka",
    keywords: "lusaka africa/lusaka cat central africa standard time",
  },
  {
    id: "Europe/Luxembourg",
    city: "Luxembourg",
    keywords:
      "luxembourg europe/luxembourg cet cest central european standard time",
  },
  {
    id: "America/Maceio",
    city: "Maceio",
    keywords: "maceio america/maceio brt brasilia standard time",
  },
  {
    id: "Antarctica/Macquarie",
    city: "Macquarie",
    keywords:
      "macquarie antarctica/macquarie aest aedt eastern australia standard time",
  },
  {
    id: "Atlantic/Madeira",
    city: "Madeira",
    keywords:
      "madeira atlantic/madeira wet west western european standard time",
  },
  {
    id: "Indian/Mahe",
    city: "Mahe",
    keywords: "mahe indian/mahe sct seychelles standard time",
  },
  {
    id: "Pacific/Majuro",
    city: "Majuro",
    keywords: "majuro pacific/majuro mht marshall islands standard time",
  },
  {
    id: "Asia/Makassar",
    city: "Makassar",
    keywords: "makassar asia/makassar wita central indonesia standard time",
  },
  {
    id: "Africa/Malabo",
    city: "Malabo",
    keywords: "malabo africa/malabo wat west africa standard time",
  },
  {
    id: "Indian/Maldives",
    city: "Maldives",
    keywords: "maldives indian/maldives mvt maldives standard time",
  },
  {
    id: "Europe/Malta",
    city: "Malta",
    keywords: "malta europe/malta cet cest central european standard time",
  },
  {
    id: "America/Managua",
    city: "Managua",
    keywords: "managua america/managua cst central standard time",
  },
  {
    id: "America/Manaus",
    city: "Manaus",
    keywords: "manaus america/manaus amt amazon standard time",
  },
  {
    id: "Africa/Maputo",
    city: "Maputo",
    keywords: "maputo africa/maputo cat central africa standard time",
  },
  {
    id: "America/Indiana/Marengo",
    city: "Marengo",
    keywords: "marengo america/indiana/marengo est edt eastern standard time",
  },
  {
    id: "Europe/Mariehamn",
    city: "Mariehamn",
    keywords:
      "mariehamn europe/mariehamn eet eest eastern european standard time",
  },
  {
    id: "America/Marigot",
    city: "Marigot",
    keywords: "marigot america/marigot ast atlantic standard time",
  },
  {
    id: "Pacific/Marquesas",
    city: "Marquesas",
    keywords: "marquesas pacific/marquesas mart marquesas standard time",
  },
  {
    id: "America/Martinique",
    city: "Martinique",
    keywords: "martinique america/martinique ast atlantic standard time",
  },
  {
    id: "Africa/Maseru",
    city: "Maseru",
    keywords: "maseru africa/maseru sast south africa standard time",
  },
  {
    id: "America/Matamoros",
    city: "Matamoros",
    keywords: "matamoros america/matamoros cst cdt central standard time",
  },
  {
    id: "Antarctica/Mawson",
    city: "Mawson",
    keywords: "mawson antarctica/mawson mawt mawson standard time",
  },
  {
    id: "Indian/Mayotte",
    city: "Mayotte",
    keywords: "mayotte indian/mayotte eat east africa standard time",
  },
  {
    id: "America/Mazatlan",
    city: "Mazatlan",
    keywords:
      "mazatlan america/mazatlan hnpmx hepmx mexican pacific standard time",
  },
  {
    id: "Africa/Mbabane",
    city: "Mbabane",
    keywords: "mbabane africa/mbabane sast south africa standard time",
  },
  {
    id: "Antarctica/McMurdo",
    city: "McMurdo",
    keywords: "mcmurdo antarctica/mcmurdo nzst nzdt new zealand standard time",
  },
  {
    id: "America/Mendoza",
    city: "Mendoza",
    keywords: "mendoza america/mendoza art argentina standard time",
  },
  {
    id: "America/Menominee",
    city: "Menominee",
    keywords: "menominee america/menominee cst cdt central standard time",
  },
  {
    id: "America/Merida",
    city: "Merida",
    keywords: "merida america/merida cst cdt central mexico standard time",
  },
  {
    id: "America/Metlakatla",
    city: "Metlakatla",
    keywords: "metlakatla america/metlakatla akst akdt alaska standard time",
  },
  {
    id: "Pacific/Midway",
    city: "Midway",
    keywords: "midway pacific/midway sst samoa standard time",
  },
  {
    id: "America/Miquelon",
    city: "Miquelon",
    keywords:
      "miquelon america/miquelon hnpm hepm st. pierre & miquelon standard time",
  },
  {
    id: "Africa/Mogadishu",
    city: "Mogadishu",
    keywords: "mogadishu africa/mogadishu eat east africa standard time",
  },
  {
    id: "Europe/Monaco",
    city: "Monaco",
    keywords: "monaco europe/monaco cet cest central european standard time",
  },
  {
    id: "America/Moncton",
    city: "Moncton",
    keywords: "moncton america/moncton ast adt atlantic standard time",
  },
  {
    id: "America/Monterrey",
    city: "Monterrey",
    keywords:
      "monterrey america/monterrey cst cdt central mexico standard time",
  },
  {
    id: "America/Kentucky/Monticello",
    city: "Monticello",
    keywords:
      "monticello america/kentucky/monticello est edt eastern standard time",
  },
  {
    id: "America/Montreal",
    city: "Montreal",
    keywords: "montreal america/montreal est edt eastern standard time",
  },
  {
    id: "America/Montserrat",
    city: "Montserrat",
    keywords: "montserrat america/montserrat ast atlantic standard time",
  },
  {
    id: "Asia/Muscat",
    city: "Muscat",
    keywords: "muscat asia/muscat gst gulf standard time",
  },
  {
    id: "America/Nassau",
    city: "Nassau",
    keywords: "nassau america/nassau est edt eastern standard time",
  },
  {
    id: "Pacific/Nauru",
    city: "Nauru",
    keywords: "nauru pacific/nauru nrt nauru standard time",
  },
  {
    id: "Africa/Ndjamena",
    city: "Ndjamena",
    keywords: "ndjamena africa/ndjamena wat west africa standard time",
  },
  {
    id: "America/North_Dakota/New_Salem",
    city: "New Salem",
    keywords:
      "new salem america/north_dakota/new_salem cst cdt central standard time",
  },
  {
    id: "Africa/Niamey",
    city: "Niamey",
    keywords: "niamey africa/niamey wat west africa standard time",
  },
  {
    id: "Asia/Nicosia",
    city: "Nicosia",
    keywords: "nicosia asia/nicosia eet eest eastern european standard time",
  },
  {
    id: "Pacific/Niue",
    city: "Niue",
    keywords: "niue pacific/niue nut niue standard time",
  },
  {
    id: "America/Nome",
    city: "Nome",
    keywords: "nome america/nome akst akdt alaska standard time",
  },
  {
    id: "Pacific/Norfolk",
    city: "Norfolk",
    keywords: "norfolk pacific/norfolk nft nfdt norfolk island standard time",
  },
  {
    id: "Africa/Nouakchott",
    city: "Nouakchott",
    keywords: "nouakchott africa/nouakchott gmt greenwich mean standard time",
  },
  {
    id: "Asia/Novokuznetsk",
    city: "Novokuznetsk",
    keywords: "novokuznetsk asia/novokuznetsk krat krasnoyarsk standard time",
  },
  {
    id: "Asia/Novosibirsk",
    city: "Novosibirsk",
    keywords: "novosibirsk asia/novosibirsk novt novosibirsk standard time",
  },
  {
    id: "America/Ojinaga",
    city: "Ojinaga",
    keywords: "ojinaga america/ojinaga mst mdt mountain standard time",
  },
  {
    id: "Asia/Oral",
    city: "Oral",
    keywords: "oral asia/oral almt west kazakhstan standard time",
  },
  {
    id: "Africa/Ouagadougou",
    city: "Ouagadougou",
    keywords: "ouagadougou africa/ouagadougou gmt greenwich mean standard time",
  },
  {
    id: "Pacific/Palau",
    city: "Palau",
    keywords: "palau pacific/palau pwt palau standard time",
  },
  {
    id: "Antarctica/Palmer",
    city: "Palmer",
    keywords: "palmer antarctica/palmer art argentina standard time",
  },
  {
    id: "America/Paramaribo",
    city: "Paramaribo",
    keywords: "paramaribo america/paramaribo srt suriname standard time",
  },
  {
    id: "America/Indiana/Petersburg",
    city: "Petersburg",
    keywords:
      "petersburg america/indiana/petersburg est edt eastern standard time",
  },
  {
    id: "Asia/Phnom_Penh",
    city: "Phnom Penh",
    keywords: "phnom penh asia/phnom_penh ict indochina standard time",
  },
  {
    id: "Pacific/Pitcairn",
    city: "Pitcairn",
    keywords: "pitcairn pacific/pitcairn pst pitcairn standard time",
  },
  {
    id: "Europe/Podgorica",
    city: "Podgorica",
    keywords:
      "podgorica europe/podgorica cet cest central european standard time",
  },
  {
    id: "Pacific/Ponape",
    city: "Ponape",
    keywords: "ponape pacific/ponape pont ponape standard time",
  },
  {
    id: "Asia/Pontianak",
    city: "Pontianak",
    keywords: "pontianak asia/pontianak wib western indonesia standard time",
  },
  {
    id: "America/Port_of_Spain",
    city: "Port of Spain",
    keywords: "port of spain america/port_of_spain ast atlantic standard time",
  },
  {
    id: "America/Port-au-Prince",
    city: "Port-au-Prince",
    keywords:
      "port-au-prince america/port-au-prince est edt eastern standard time",
  },
  {
    id: "America/Porto_Velho",
    city: "Porto Velho",
    keywords: "porto velho america/porto_velho amt amazon standard time",
  },
  {
    id: "Africa/Porto-Novo",
    city: "Porto-Novo",
    keywords: "porto-novo africa/porto-novo wat west africa standard time",
  },
  {
    id: "America/Punta_Arenas",
    city: "Punta Arenas",
    keywords: "punta arenas america/punta_arenas clt chile standard time",
  },
  {
    id: "Asia/Pyongyang",
    city: "Pyongyang",
    keywords: "pyongyang asia/pyongyang kst korean standard time",
  },
  {
    id: "Asia/Qostanay",
    city: "Qostanay",
    keywords: "qostanay asia/qostanay almt east kazakhstan standard time",
  },
  {
    id: "Asia/Qyzylorda",
    city: "Qyzylorda",
    keywords: "qyzylorda asia/qyzylorda almt west kazakhstan standard time",
  },
  {
    id: "Asia/Rangoon",
    city: "Rangoon",
    keywords: "rangoon asia/rangoon mmt myanmar standard time",
  },
  {
    id: "America/Rankin_Inlet",
    city: "Rankin Inlet",
    keywords: "rankin inlet america/rankin_inlet cst cdt central standard time",
  },
  {
    id: "Pacific/Rarotonga",
    city: "Rarotonga",
    keywords: "rarotonga pacific/rarotonga ckt cook islands standard time",
  },
  {
    id: "America/Recife",
    city: "Recife",
    keywords: "recife america/recife brt brasilia standard time",
  },
  {
    id: "America/Regina",
    city: "Regina",
    keywords: "regina america/regina cst central standard time",
  },
  {
    id: "America/Resolute",
    city: "Resolute",
    keywords: "resolute america/resolute cst cdt central standard time",
  },
  {
    id: "Indian/Reunion",
    city: "Reunion",
    keywords: "reunion indian/reunion ret réunion standard time",
  },
  {
    id: "America/Rio_Branco",
    city: "Rio Branco",
    keywords: "rio branco america/rio_branco act acre standard time",
  },
  {
    id: "America/Argentina/Rio_Gallegos",
    city: "Rio Gallegos",
    keywords:
      "rio gallegos america/argentina/rio_gallegos art argentina standard time",
  },
  {
    id: "Antarctica/Rothera",
    city: "Rothera",
    keywords: "rothera antarctica/rothera art argentina standard time",
  },
  {
    id: "Asia/Saigon",
    city: "Saigon",
    keywords: "saigon asia/saigon ict indochina standard time",
  },
  {
    id: "Pacific/Saipan",
    city: "Saipan",
    keywords: "saipan pacific/saipan chst chamorro standard time",
  },
  {
    id: "Asia/Sakhalin",
    city: "Sakhalin",
    keywords: "sakhalin asia/sakhalin sakt sakhalin standard time",
  },
  {
    id: "America/Argentina/Salta",
    city: "Salta",
    keywords: "salta america/argentina/salta art argentina standard time",
  },
  {
    id: "Europe/Samara",
    city: "Samara",
    keywords: "samara europe/samara samt samara standard time",
  },
  {
    id: "Asia/Samarkand",
    city: "Samarkand",
    keywords: "samarkand asia/samarkand uzt uzbekistan standard time",
  },
  {
    id: "America/Argentina/San_Juan",
    city: "San Juan",
    keywords: "san juan america/argentina/san_juan art argentina standard time",
  },
  {
    id: "America/Argentina/San_Luis",
    city: "San Luis",
    keywords: "san luis america/argentina/san_luis art argentina standard time",
  },
  {
    id: "Europe/San_Marino",
    city: "San Marino",
    keywords:
      "san marino europe/san_marino cet cest central european standard time",
  },
  {
    id: "America/Santa_Isabel",
    city: "Santa Isabel",
    keywords: "santa isabel america/santa_isabel pst pdt pacific standard time",
  },
  {
    id: "America/Santarem",
    city: "Santarem",
    keywords: "santarem america/santarem brt brasilia standard time",
  },
  {
    id: "Africa/Sao_Tome",
    city: "Sao Tome",
    keywords: "sao tome africa/sao_tome gmt greenwich mean standard time",
  },
  {
    id: "Europe/Sarajevo",
    city: "Sarajevo",
    keywords:
      "sarajevo europe/sarajevo cet cest central european standard time",
  },
  {
    id: "Europe/Saratov",
    city: "Saratov",
    keywords: "saratov europe/saratov samt samara standard time",
  },
  {
    id: "America/Scoresbysund",
    city: "Scoresbysund",
    keywords:
      "scoresbysund america/scoresbysund hneg heeg east greenland standard time",
  },
  {
    id: "Europe/Simferopol",
    city: "Simferopol",
    keywords:
      "simferopol europe/simferopol eet eest eastern european standard time",
  },
  {
    id: "America/Sitka",
    city: "Sitka",
    keywords: "sitka america/sitka akst akdt alaska standard time",
  },
  {
    id: "Europe/Skopje",
    city: "Skopje",
    keywords: "skopje europe/skopje cet cest central european standard time",
  },
  {
    id: "Asia/Srednekolymsk",
    city: "Srednekolymsk",
    keywords:
      "srednekolymsk asia/srednekolymsk sret srednekolymsk standard time",
  },
  {
    id: "America/St_Barthelemy",
    city: "St Barthelemy",
    keywords: "st barthelemy america/st_barthelemy ast atlantic standard time",
  },
  {
    id: "Atlantic/St_Helena",
    city: "St Helena",
    keywords: "st helena atlantic/st_helena gmt greenwich mean standard time",
  },
  {
    id: "America/St_Kitts",
    city: "St Kitts",
    keywords: "st kitts america/st_kitts ast atlantic standard time",
  },
  {
    id: "America/St_Lucia",
    city: "St Lucia",
    keywords: "st lucia america/st_lucia ast atlantic standard time",
  },
  {
    id: "America/St_Thomas",
    city: "St Thomas",
    keywords: "st thomas america/st_thomas ast atlantic standard time",
  },
  {
    id: "America/St_Vincent",
    city: "St Vincent",
    keywords: "st vincent america/st_vincent ast atlantic standard time",
  },
  {
    id: "Atlantic/Stanley",
    city: "Stanley",
    keywords: "stanley atlantic/stanley fkst falkland islands standard time",
  },
  {
    id: "America/Swift_Current",
    city: "Swift Current",
    keywords: "swift current america/swift_current cst central standard time",
  },
  {
    id: "Antarctica/Syowa",
    city: "Syowa",
    keywords: "syowa antarctica/syowa ast arabian standard time",
  },
  {
    id: "Pacific/Tahiti",
    city: "Tahiti",
    keywords: "tahiti pacific/tahiti taht tahiti standard time",
  },
  {
    id: "Pacific/Tarawa",
    city: "Tarawa",
    keywords: "tarawa pacific/tarawa gilt gilbert islands standard time",
  },
  {
    id: "America/Tegucigalpa",
    city: "Tegucigalpa",
    keywords: "tegucigalpa america/tegucigalpa cst central standard time",
  },
  {
    id: "America/Indiana/Tell_City",
    city: "Tell City",
    keywords:
      "tell city america/indiana/tell_city cst cdt central standard time",
  },
  {
    id: "Asia/Thimphu",
    city: "Thimphu",
    keywords: "thimphu asia/thimphu bt bhutan standard time",
  },
  {
    id: "America/Thule",
    city: "Thule",
    keywords: "thule america/thule ast adt atlantic standard time",
  },
  {
    id: "Europe/Tirane",
    city: "Tirane",
    keywords: "tirane europe/tirane cet cest central european standard time",
  },
  {
    id: "Asia/Tomsk",
    city: "Tomsk",
    keywords: "tomsk asia/tomsk omst omsk standard time",
  },
  {
    id: "America/Tortola",
    city: "Tortola",
    keywords: "tortola america/tortola ast atlantic standard time",
  },
  {
    id: "Africa/Tripoli",
    city: "Tripoli",
    keywords: "tripoli africa/tripoli eet eastern european standard time",
  },
  {
    id: "Antarctica/Troll",
    city: "Troll",
    keywords: "troll antarctica/troll gmt troll standard time",
  },
  {
    id: "Pacific/Truk",
    city: "Truk",
    keywords: "truk pacific/truk chut chuuk standard time",
  },
  {
    id: "America/Argentina/Tucuman",
    city: "Tucuman",
    keywords: "tucuman america/argentina/tucuman art argentina standard time",
  },
  {
    id: "Asia/Ulaanbaatar",
    city: "Ulaanbaatar",
    keywords: "ulaanbaatar asia/ulaanbaatar ulat ulaanbaatar standard time",
  },
  {
    id: "Europe/Ulyanovsk",
    city: "Ulyanovsk",
    keywords: "ulyanovsk europe/ulyanovsk msk moscow standard time",
  },
  {
    id: "Asia/Urumqi",
    city: "Urumqi",
    keywords: "urumqi asia/urumqi cst china standard time",
  },
  {
    id: "America/Argentina/Ushuaia",
    city: "Ushuaia",
    keywords: "ushuaia america/argentina/ushuaia art argentina standard time",
  },
  {
    id: "Asia/Ust-Nera",
    city: "Ust-Nera",
    keywords: "ust-nera asia/ust-nera vlat vladivostok standard time",
  },
  {
    id: "Europe/Vaduz",
    city: "Vaduz",
    keywords: "vaduz europe/vaduz cet cest central european standard time",
  },
  {
    id: "Europe/Vatican",
    city: "Vatican",
    keywords: "vatican europe/vatican cet cest central european standard time",
  },
  {
    id: "America/Indiana/Vevay",
    city: "Vevay",
    keywords: "vevay america/indiana/vevay est edt eastern standard time",
  },
  {
    id: "Asia/Vientiane",
    city: "Vientiane",
    keywords: "vientiane asia/vientiane ict indochina standard time",
  },
  {
    id: "America/Indiana/Vincennes",
    city: "Vincennes",
    keywords:
      "vincennes america/indiana/vincennes est edt eastern standard time",
  },
  {
    id: "Asia/Vladivostok",
    city: "Vladivostok",
    keywords: "vladivostok asia/vladivostok vlat vladivostok standard time",
  },
  {
    id: "Europe/Volgograd",
    city: "Volgograd",
    keywords: "volgograd europe/volgograd msk moscow standard time",
  },
  {
    id: "Antarctica/Vostok",
    city: "Vostok",
    keywords: "vostok antarctica/vostok msk+4 vostok standard time",
  },
  {
    id: "Pacific/Wake",
    city: "Wake",
    keywords: "wake pacific/wake wakt wake island standard time",
  },
  {
    id: "Pacific/Wallis",
    city: "Wallis",
    keywords: "wallis pacific/wallis wft wallis & futuna standard time",
  },
  {
    id: "America/Whitehorse",
    city: "Whitehorse",
    keywords: "whitehorse america/whitehorse mst mountain standard time",
  },
  {
    id: "America/Indiana/Winamac",
    city: "Winamac",
    keywords: "winamac america/indiana/winamac est edt eastern standard time",
  },
  {
    id: "Africa/Windhoek",
    city: "Windhoek",
    keywords: "windhoek africa/windhoek cat central africa standard time",
  },
  {
    id: "America/Yakutat",
    city: "Yakutat",
    keywords: "yakutat america/yakutat akst akdt alaska standard time",
  },
  {
    id: "Europe/Zagreb",
    city: "Zagreb",
    keywords: "zagreb europe/zagreb cet cest central european standard time",
  },
];
