name: Build Docker image
on: workflow_dispatch

jobs:
  publish:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get branch name
        id: extractGitBranch
        run: echo "branchName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Build and publish image
        uses: docker/build-push-action@v6
        with:
          file: ./apps/web/Dockerfile
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            SELF_HOSTED=true
